In [9]:
%matplotlib inline
import pandas as pd
import numpy as np
from textblob import TextBlob
import matplotlib as mpl
import matplotlib.pyplot as plt
import csv
import _pickle as cPickle
from scipy.io import loadmat
from sklearn.svm import SVC
import seaborn as sns

sns.set_context('notebook')
sns.set_style('white')

import nltk
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.model_selection import (
    train_test_split, GridSearchCV, StratifiedKFold,
    cross_val_score, learning_curve
)
from sklearn.metrics import classification_report, f1_score, confusion_matrix, roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB

In [10]:
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')

import textblob.download_corpora
textblob.download_corpora.download_all()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\brown.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package conll2000 to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\conll2000.zip.
[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.

In [11]:
df=pd.read_csv("Training.txt",sep="\t", names=['liked','text'],encoding="utf-8");
df.head(3)

   liked                                               text
0      1                      India is developing countries
1      1            The Da Vinci Code book is just awesome.
2      1  this was the first clive cussler i've ever rea...

In [12]:
print(len(df))

6931

In [13]:
df.groupby('liked').describe()

       text
      count unique                   top freq
liked
0      2975    559  I hate Harry Potter.   85
1      3956    744  I love Harry Potter.  167

In [14]:
def tokens(review):
    return TextBlob(review).words

In [15]:
df.head().text.apply(tokens)

0                   [India, is, developing, countries]
1      [The, Da, Vinci, Code, book, is, just, awesome]
2    [this, was, the, first, clive, cussler, i, 've...
3             [i, liked, the, Da, Vinci, Code, a, lot]
4             [i, liked, the, Da, Vinci, Code, a, lot]
Name: text, dtype: object

In [16]:
TextBlob("ready was not a good movie").tags
#nltk.help.upenn_tagset('JJ')

[('ready', 'NN'),
 ('was', 'VBD'),
 ('not', 'RB'),
 ('a', 'DT'),
 ('good', 'JJ'),
 ('movie', 'NN')]

In [17]:
def to_lemmas(review):
    wordss = TextBlob(review.lower()).words
    # for each word, take its "base form" = lemma 
    return [word.lemma for word in wordss]

df.text.head().apply(to_lemmas)

0                     [india, is, developing, country]
1      [the, da, vinci, code, book, is, just, awesome]
2    [this, wa, the, first, clive, cussler, i, 've,...
3             [i, liked, the, da, vinci, code, a, lot]
4             [i, liked, the, da, vinci, code, a, lot]
Name: text, dtype: object

In [18]:
from nltk.stem.wordnet import WordNetLemmatizer
lmtzr = WordNetLemmatizer()
lmtzr.lemmatize('octopi')
#nltk

'octopus'

In [19]:
bow_transformer = CountVectorizer(analyzer=to_lemmas).fit(df['text'])
print(len(bow_transformer.vocabulary_))

2114

In [20]:
review1=df['text'][3]
print(review1)

i liked the Da Vinci Code a lot.

In [21]:
bow=bow_transformer.transform([review1])
print(bow)
bow.shape

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (1, 2114)>
  Coords	Values
  (0, 42)	1
  (0, 369)	1
  (0, 458)	1
  (0, 950)	1
  (0, 1123)	1
  (0, 1152)	1
  (0, 1838)	1
  (0, 1977)	1

(1, 2114)

In [23]:
print(bow_transformer.get_feature_names_out()[372])

code-other

In [24]:
review_bow = bow_transformer.transform(df['text'])
print( 'sparse matrix shape:', review_bow.shape)
print('number of non-zeros:', review_bow.nnz) #learn this
print( 'sparsity: %.2f%%' % (100.0 * review_bow.nnz))

sparse matrix shape: (6931, 2114)
number of non-zeros: 71297
sparsity: 7129700.00%

In [25]:
tfidf_transformer =TfidfTransformer().fit(review_bow)
review_tfidf = tfidf_transformer.transform(review_bow)
review_tfidf.shape

(6931, 2114)

In [26]:
text_train, text_test, liked_train, liked_test = train_test_split(df['text'], df['liked'], test_size=0.2)
print(len(text_train), len(text_test), len(text_train) , len(text_test))

5544 1387 5544 1387

In [27]:
classifier = SVC(kernel='linear')

In [28]:
pipeline_svm = Pipeline([
    ('bow', CountVectorizer(analyzer=to_lemmas)),
    ('tfidf', TfidfTransformer()),
    ('classifier', SVC()),
])

In [29]:
# pipeline parameters to automatically explore and tune
param_svm = [
  {'classifier__C': [1, 10, 100, 1000], 'classifier__kernel': ['linear']},
  {'classifier__C': [1, 10, 100, 1000], 'classifier__gamma': [0.001, 0.0001], 'classifier__kernel': ['rbf']},
]

In [32]:
grid_svm = GridSearchCV(
    pipeline_svm, #object used to fit the data
    param_grid=param_svm, 
    refit=True,  # fit using all data, on the best detected classifier
    n_jobs=-1,  # number of cores to use for parallelization; -1 for "all cores" i.e. to run on all CPUs
    scoring='accuracy',#optimizing parameter
    cv=StratifiedKFold(n_splits=5),
)

In [34]:
%time classifier = grid_svm.fit(text_train, liked_train) # find the best combination from param_svm
print(classifier.cv_results_)

CPU times: total: 1.92 s
Wall time: 49.5 s
{'mean_fit_time': array([2.58059268, 2.72344441, 2.82414927, 2.59287863, 6.61674547,
       6.85583401, 5.37372751, 6.47840133, 2.66736188, 4.75019693,
       2.53086677, 2.56600032]), 'std_fit_time': array([0.15006809, 0.2060391 , 0.21166364, 0.22427682, 0.18971279,
       0.29641494, 0.10855529, 0.37075459, 0.18494388, 0.1892713 ,
       0.17235539, 0.08069112]), 'mean_score_time': array([0.64566364, 0.63280549, 0.67322283, 0.61300797, 1.40246263,
       1.33313327, 1.18071961, 1.36064963, 0.66629457, 1.08778896,
       0.62253847, 0.60559773]), 'std_score_time': array([0.04403863, 0.02582581, 0.02465935, 0.03172439, 0.05041156,
       0.07586026, 0.05350831, 0.09351915, 0.04700491, 0.03846102,
       0.03144167, 0.04844448]), 'param_classifier__C': masked_array(data=[1, 10, 100, 1000, 1, 1, 10, 10, 100, 100, 1000, 1000],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'param_classifier__kernel': masked_array(data=['linear', 'linear', 'linear', 'linear', 'rbf', 'rbf',
                   'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_classifier__gamma': masked_array(data=[--, --, --, --, 0.001, 0.0001, 0.001, 0.0001, 0.001,
                   0.0001, 0.001, 0.0001],
             mask=[ True,  True,  True,  True, False, False, False, False,
                   False, False, False, False],
       fill_value=1e+20), 'params': [{'classifier__C': 1, 'classifier__kernel': 'linear'}, {'classifier__C': 10, 'classifier__kernel': 'linear'}, {'classifier__C': 100, 'classifier__kernel': 'linear'}, {'classifier__C': 1000, 'classifier__kernel': 'linear'}, {'classifier__C': 1, 'classifier__gamma': 0.001, 'classifier__kernel': 'rbf'}, {'classifier__C': 1, 'classifier__gamma': 0.0001, 'classifier__kernel': 'rbf'}, {'classifier__C': 10, 'classifier__gamma': 0.001, 'classifier__kernel': 'rbf'}, {'classifier__C': 10, 'classifier__gamma': 0.0001, 'classifier__kernel': 'rbf'}, {'classifier__C': 100, 'classifier__gamma': 0.001, 'classifier__kernel': 'rbf'}, {'classifier__C': 100, 'classifier__gamma': 0.0001, 'classifier__kernel': 'rbf'}, {'classifier__C': 1000, 'classifier__gamma': 0.001, 'classifier__kernel': 'rbf'}, {'classifier__C': 1000, 'classifier__gamma': 0.0001, 'classifier__kernel': 'rbf'}], 'split0_test_score': array([0.99909829, 0.99639315, 0.99639315, 0.99639315, 0.56717764,
       0.56717764, 0.9792606 , 0.56717764, 0.99729486, 0.9792606 ,
       0.99639315, 0.99729486]), 'split1_test_score': array([0.99458972, 0.99458972, 0.99458972, 0.99458972, 0.56717764,
       0.56717764, 0.98016231, 0.56717764, 0.99368801, 0.98016231,
       0.99458972, 0.99368801]), 'split2_test_score': array([0.98737601, 0.98737601, 0.98737601, 0.98737601, 0.56717764,
       0.56717764, 0.96753832, 0.56717764, 0.98286745, 0.96753832,
       0.98827773, 0.98286745]), 'split3_test_score': array([0.99188458, 0.98917944, 0.98917944, 0.98917944, 0.56717764,
       0.56717764, 0.9657349 , 0.56717764, 0.98467087, 0.9657349 ,
       0.99098287, 0.98467087]), 'split4_test_score': array([0.99548736, 0.99548736, 0.99548736, 0.99548736, 0.566787  ,
       0.566787  , 0.97021661, 0.566787  , 0.98646209, 0.97021661,
       0.99638989, 0.98736462]), 'mean_test_score': array([0.99368719, 0.99260514, 0.99260514, 0.99260514, 0.56709951,
       0.56709951, 0.97258255, 0.56709951, 0.98899666, 0.97258255,
       0.99332667, 0.98917716]), 'std_test_score': array([0.00390936, 0.00362419, 0.00362419, 0.00362419, 0.00015625,
       0.00015625, 0.00599969, 0.00015625, 0.00554207, 0.00599969,
       0.00320522, 0.00547082]), 'rank_test_score': array([ 1,  3,  3,  3, 10, 10,  8, 10,  7,  8,  2,  6], dtype=int32)}

In [35]:
print(classification_report(liked_test, classifier.predict(text_test)))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       575
           1       0.99      0.99      0.99       812

    accuracy                           0.99      1387
   macro avg       0.99      0.99      0.99      1387
weighted avg       0.99      0.99      0.99      1387

In [36]:
print(classifier.predict(["the vinci code is awesome"])[0])

1